GET http://localhost:3000/movies/

GET http://localhost:3000/movies/1


POST http://localhost:3000/movies/
Content-Type: application/json

{
  "directorId": 1,
  "movieName": "New Movie",
  "leadActor": "Lead Actor"
}

PUT http://localhost:3000/movies/1
Content-Type: application/json

{
  "directorId": 2,
  "movieName": "Updated Movie",
  "leadActor": "New Lead Actor"
}

DELETE http://localhost:3000/movies/1

